repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.6
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
#  - repo: local
#    hooks:
#      - id: ty
#        name: ty check
#        entry: ty check . --ignore unresolved-import
#        language: system
#        pass_filenames: false
#        always_run: true
